### ISSUE TITLE
Nothing displayed on the jsfiddle demo with chrome 

### ISSUE THREAD

**Issue by BrianGiannini** [loredanacirstea/svg.connectable.js#1]
The example on the jsfiddle demo is not working properly on chrome with the error : 

> Cannot read property 'numberOfItems' of undefined

There are also some issues with IE on Firefox.

**Comment by loredanacirstea** [comment]
You should now be able to see the demo at least on Chrome and Firefox: https://jsfiddle.net/L2sjjc3b/79/

(There are some things that don't look ok - I'll close this issue after I'm done fixing whatever I can/have time to fix today)

https://github.com/loredanacirstea/svg.connectable.js/commit/cab2c8964db54bd847d7e29547a0991a3a0c420c

**Comment by loredanacirstea** [comment]
https://jsfiddle.net/L2sjjc3b/80/

That's the changes I could do for now. The g3 circle has a weird looking connector attachment in the jsfiddle, different that what i see on my computer. Something went wrong somewhere, but I don't currently have time to see what.

Feel free to open any new issues.

Hope it helps your usecase!
