### ISSUE TITLE
Connector stoke width

### ISSUE THREAD

**Issue by cr1t** [loredanacirstea/svg.connectable.js#4]
Hi 

Is it possible to change the stroke width, on the connector, also would it be possible to use a dotted line type stoke?

**Comment by 13djwright** [comment]
I know it is a little late, but I ran into this issue as well and found a way to solve it.
https://jsfiddle.net/13djwright/n3upd0t4/

Basically, just access the connector that gets returned, and then from there you can go in and change the stroke attribute, as well as add the stroke-dasharray attribute for a dotted line.

**Comment by cr1t** [comment]
Thanks, I managed to solve it using a css class
